// flow-typed signature: 4d6b79596eb904f8485669af9523044a
// flow-typed version: <<STUB>>/ts-progress_v^0.1.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-progress/example' {
  declare module.exports: any;
}

declare module 'ts-progress/progress' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-progress/example.js' {
  declare module.exports: $Exports<'ts-progress/example'>;
}
declare module 'ts-progress/progress.js' {
  declare module.exports: $Exports<'ts-progress/progress'>;
}
